apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: witboost-addons-adls-op-es
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStore }}
    kind: {{ .Values.externalSecrets.secretStoreType | default "ClusterSecretStore" }}
  target:
    name: azure-adls-addons-secrets
  dataFrom:
  - extract:
      key: {{ .Values.externalSecrets.extractKey }}