apiVersion: v1
kind: Service
metadata:
  name: {{ template "adlsopspname" . }}
  labels:
{{- include "adlsopsplabels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8888
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ template "adlsopspname" . }}
