apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: fake
spec:
  provider:
    fake:
      data:
        - key: "adls-op"
          valueMap:
            AZURE_TENANT_ID: azure_tenant_id
            # The following env vars are required only if authentication is done through service principal
            # (.Values.authentication.userWorkloadIdentity is false)
            AZURE_CLIENT_ID: azure_client_id
            AZURE_CLIENT_SECRET: azure_client_secret
