spring:
  application:
    name: adls-op-specific-provisioner

server:
  port: 8888

springdoc:
  swagger-ui:
    path: /docs

azure.permissions:
  clientId: ${AZURE_CLIENT_ID}
  tenantId: ${AZURE_TENANT_ID}
  clientSecret: ${AZURE_CLIENT_SECRET}
